export { SearchAnime } from '@ipcHandlers/scraper/SearchAnime';
export { RandomAnime } from '@ipcHandlers/scraper/RandomAnime';
export { InfoAnime } from '@ipcHandlers/scraper/InfoAnime';
export { SeasonsAnime } from '@ipcHandlers/scraper/SeasonsAnime';
export { EpisodesSeason } from '@ipcHandlers/scraper/EpisodesSeason';
export { UrlEpisode } from '@ipcHandlers/scraper/UrlEpisode';
export { LatestEpisodes } from '@ipcHandlers/scraper/LatestEpisodes';
export { CatalogAnime } from '@ipcHandlers/scraper/CatalogAnime';
export { AvailableLanguages } from '@ipcHandlers/scraper/AvailableLanguages'
export { ScansChapter } from '@ipcHandlers/scraper/ScansChapter';
export { ScansImg } from '@ipcHandlers/scraper/ScansImg';
export { DownloadEpisode } from '@ipcHandlers/data/DownloadEpisode';
export { DownloadList } from '@ipcHandlers/data/DownloadList';
export { DeleteDownloadEpisode } from '@ipcHandlers/data/DeleteDownloadEpisode';
export { ExportData } from '@ipcHandlers/data/ExportData';
export { ImportData } from '@ipcHandlers/data/ImportData';
